### ISSUE TITLE
consider changing the module name to github.com/jdxyw/generativeart

### ISSUE THREAD

**Issue by refs** [jdxyw/generativeart#1]
sadly when `go get`ting it it throws a tantrum:

```console
~/code/refs/generativeart
❯ go get github.com/jdxyw/generativeart
go: github.com/jdxyw/generativeart upgrade => v0.0.0-20210303093834-f33224c60df0
go get: github.com/jdxyw/generativeart@v0.0.0-20210303093834-f33224c60df0: parsing go.mod:
	module declares its path as: generativeart
	        but was required as: github.com/jdxyw/generativeart
```

I'd open a PR myself but it requires updating all import paths all over the place. I might just do that 🤔

**Comment by jdxyw** [comment]
Did you use the go 1.16?

**Comment by jdxyw** [comment]
I have confirmed that this issue only happed for go 1.16. It works for 1.15 and 1.14. Anyway, since the latest go version requires it, I would merge this PR. Thanks.
