### ISSUE TITLE
undefined: common.Plasma

### ISSUE THREAD

**Issue by 400lbhacker** [jdxyw/generativeart#7]
I am trying to run the go files, using the command line:
go run example.go AND also: go build example.go 
------------
I recieve the following error: 

# command-line-arguments
.\example_dotline.go:18:19: undefined: common.Plasma

**Comment by hossein1376** [comment]
Hey, it seems like you have removed (or maybe renamed) the plasma color found in the common.Plasma route, but it is still being used in two of the Art Types mentioned in the readme file: Dot Line, Random Circle

From your commit for this issue, it seems like that you have went with DarkPink instead.

My regards
